language: ruby
rvm:
  - 2.3.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
deploy:
  provider: heroku
  api_key:
    secure: w5kXcUZ759ElMsgbqT6a9BD9cFPFxc6xcM5vtESTABLrncCa5rHiogb+uI0T/tADE5JkNzR4QyuumrtRDNj1Hgv8t62F7YbHEaRRBe5baTkKLNL5hXZ3uSL97fjxcriMvtG0J2E13RFnmRTdIrJXNLBhEYjpsXj/LvrbIS+BW21GaDGRvKW8EkJV9A7hdqrGmgoIK1G0oKJR/KPqdGpXTvdNgoFafvtkCvKBbkzEdFQg9gQHurtSwLGfzrtApOKzgO219Cx3jOKJyxvqty9rxNDYdG/0slueE3ggKpgggfWsqCSpl6wSXmu3IBT+v1nsl/eE2NMc8gS0NaT+vJnLfSaJT1v4h570RqWT1xezkeJ+WA+pB08Gl5K+LOvWwtnUSUzX1pqIsva+g06s6GC7BN9nqmjJKEKiYIO7dxq9ubT62ii2ubi5ILpmlsk82fy03x3Oucv9Nw5BfLv91z7hvGUp1fGDYzy4GMEPtXM0N4PbZ9tVL1qfyynNIvxcXAzi1tLXvQOQ5jViNDMeVNiiq3RpBPjvzQqQZENIpCS8SWnP7sGIOx3YRg9fA2ihLV1dtIhuWnm5mS2NYq7yl9e5gygujYkVsV/6UC5wviYv83GFhkuedIup6gM+WPU2zMjZAjYv1LJVVdmbK127+0WepEM4bZN4oS2I9XjEM8tr/aI=
  app: guardian-app-v1
  on:
    repo: fhboswell/Guardian
