

development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: henryboswell
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: 
  password:

